### ISSUE TITLE
http://127.0.0.1:8080/api/public/stock_zh_a_hist 返回数据错误

### ISSUE THREAD

**Issue by matakk** [akfamily/aktools#178]

**Comment by matakk** [comment]
大量的重复的是这个：

 ```
  {
      "开盘" : 49.0,
      "成交量" : 1,
      "成交额" : 5000.0,
      "振幅" : 0.0,
      "换手率" : 0.0,
      "收盘" : 49.0,
      "日期" : "1991-04-03T00:00:00.000",
      "最低" : 49.0,
      "最高" : 49.0,
      "涨跌幅" : 22.50,
      "涨跌额" : 9.0,
      "股票代码" : "000001"
   },
```


日志出现：
INFO:     127.0.0.1:13516 - "GET /version HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\ProgramData\anaconda3\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\aktools\main.py", line 77, in get_version
    "ak_latest_version": get_latest_version("akshare"),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\aktools\utils.py", line 31, in get_latest_version
    .text.strip()
     ^^^^
AttributeError: 'NoneType' object has no attribute 'text'
INFO:     127.0.0.1:13518 - "GET /api/public/stock_zh_a_hist HTTP/1.1" 200 OK




访问：http://127.0.0.1:8080/version
结果是：Internal Server Error 
日志以上的上面的错误

我的刚刚安装的，都是最新的版本
python是anacodnda 2024.10的版本。
多谢！

**Comment by albertandking** [comment]
目前接口测试正常
