### ISSUE TITLE
部署在服务器，访问次数多了，就会报如下多错误

### ISSUE THREAD

**Issue by xsstomy** [akfamily/aktools#61]
系统 cenos 7

报错如下

```python
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/root/miniconda3/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/root/miniconda3/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f12a4250be0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='80.push2.eastmoney.com', port=80): Max retries exceeded with url: /api/qt/clist/get?pn=1&pz=5000&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&fid=f3&fs=m%3A0+t%3A6%2Cm%3A0+t%3A80&fields=f12&_=1623833739532 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12a4250be0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 364, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/miniconda3/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/root/miniconda3/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/root/miniconda3/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/miniconda3/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/root/miniconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.9/site-packages/aktools/core/api.py", line 128, in root
    received_df = eval("ak." + item_id + f"({eval_str})")
  File "<string>", line 1, in <module>
  File "/root/miniconda3/lib/python3.9/site-packages/akshare/stock/stock_info_em.py", line 23, in stock_individual_info_em
    code_id_dict = code_id_map_em()
  File "/root/miniconda3/lib/python3.9/site-packages/akshare/stock_feature/stock_hist_em.py", line 253, in code_id_map_em
    r = requests.get(url, params=params)
  File "/root/miniconda3/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='80.push2.eastmoney.com', port=80): Max retries exceeded with url: /api/qt/clist/get?pn=1&pz=5000&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&fid=f3&fs=m%3A0+t%3A6%2Cm%3A0+t%3A80&fields=f12&_=1623833739532 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12a4250be0>: Failed to establish a new connection: [Errno 110] Connection timed out'))`

**Comment by jindaxiang** [comment]
> 系统 cenos 7
> 
> 报错如下
> 
> ```python
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/root/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
>     raise err
>   File "/root/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
>     sock.connect(sa)
> TimeoutError: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
>     httplib_response = self._make_request(
>   File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
>     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
>   File "/root/miniconda3/lib/python3.9/http/client.py", line 1253, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/root/miniconda3/lib/python3.9/http/client.py", line 1299, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/root/miniconda3/lib/python3.9/http/client.py", line 1248, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/root/miniconda3/lib/python3.9/http/client.py", line 1008, in _send_output
>     self.send(msg)
>   File "/root/miniconda3/lib/python3.9/http/client.py", line 948, in send
>     self.connect()
>   File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
>     conn = self._new_conn()
>   File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f12a4250be0>: Failed to establish a new connection: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
>     resp = conn.urlopen(
>   File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
>     retries = retries.increment(
>   File "/root/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='80.push2.eastmoney.com', port=80): Max retries exceeded with url: /api/qt/clist/get?pn=1&pz=5000&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&fid=f3&fs=m%3A0+t%3A6%2Cm%3A0+t%3A80&fields=f12&_=1623833739532 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12a4250be0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/miniconda3/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 364, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "/root/miniconda3/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
>     return await self.app(scope, receive, send)
>   File "/root/miniconda3/lib/python3.9/site-packages/fastapi/applications.py", line 212, in __call__
>     await super().__call__(scope, receive, send)
>   File "/root/miniconda3/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/root/miniconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
>     raise exc
>   File "/root/miniconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "/root/miniconda3/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
>     raise exc
>   File "/root/miniconda3/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "/root/miniconda3/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
>     await route.handle(scope, receive, send)
>   File "/root/miniconda3/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
>     await self.app(scope, receive, send)
>   File "/root/miniconda3/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
>     response = await func(request)
>   File "/root/miniconda3/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
>     raw_response = await run_endpoint_function(
>   File "/root/miniconda3/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>   File "/root/miniconda3/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
>     return await anyio.to_thread.run_sync(func, *args)
>   File "/root/miniconda3/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
>   File "/root/miniconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
>     return await future
>   File "/root/miniconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
>     result = context.run(func, *args)
>   File "/root/miniconda3/lib/python3.9/site-packages/aktools/core/api.py", line 128, in root
>     received_df = eval("ak." + item_id + f"({eval_str})")
>   File "<string>", line 1, in <module>
>   File "/root/miniconda3/lib/python3.9/site-packages/akshare/stock/stock_info_em.py", line 23, in stock_individual_info_em
>     code_id_dict = code_id_map_em()
>   File "/root/miniconda3/lib/python3.9/site-packages/akshare/stock_feature/stock_hist_em.py", line 253, in code_id_map_em
>     r = requests.get(url, params=params)
>   File "/root/miniconda3/lib/python3.9/site-packages/requests/api.py", line 75, in get
>     return request('get', url, params=params, **kwargs)
>   File "/root/miniconda3/lib/python3.9/site-packages/requests/api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/root/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/root/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
>     r = adapter.send(request, **kwargs)
>   File "/root/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='80.push2.eastmoney.com', port=80): Max retries exceeded with url: /api/qt/clist/get?pn=1&pz=5000&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&fid=f3&fs=m%3A0+t%3A6%2Cm%3A0+t%3A80&fields=f12&_=1623833739532 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12a4250be0>: Failed to establish a new connection: [Errno 110] Connection timed out'))`
> ```

建议控制访问的频率，应该是被目标服务器封禁 IP 了

**Comment by xsstomy** [comment]
@jindaxiang  重启服务，就可以继续访问的啊。如果是禁止 IP 了，应该是继续请求失败的啊。
