### ISSUE TITLE
版本 0.0.62 访问接口会报缺少 favicon.ico 错误

### ISSUE THREAD

**Issue by xsstomy** [akfamily/aktools#66]
错误内容如下

```
INFO:     Started server process [24762]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8085 (Press CTRL+C to quit)
INFO:     127.0.0.1:47882 - "GET /api/public/stock_sh_a_spot_em HTTP/1.0" 200 OK
INFO:     127.0.0.1:47886 - "GET /favicon.ico HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/responses.py", line 318, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "/root/anaconda3/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/root/anaconda3/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/anaconda3/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [Errno 2] No such file or directory: '../favicon.ico'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/anaconda3/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/lib/python3.7/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/anaconda3/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/root/anaconda3/lib/python3.7/site-packages/starlette/responses.py", line 321, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path ../favicon.ico does not exist.
```

**Comment by jindaxiang** [comment]
> 错误内容如下
> 
> ```
> INFO:     Started server process [24762]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://127.0.0.1:8085 (Press CTRL+C to quit)
> INFO:     127.0.0.1:47882 - "GET /api/public/stock_sh_a_spot_em HTTP/1.0" 200 OK
> INFO:     127.0.0.1:47886 - "GET /favicon.ico HTTP/1.0" 500 Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/responses.py", line 318, in __call__
>     stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
>   File "/root/anaconda3/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
>     func, *args, cancellable=cancellable, limiter=limiter
>   File "/root/anaconda3/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "/root/anaconda3/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
>     result = context.run(func, *args)
> FileNotFoundError: [Errno 2] No such file or directory: '../favicon.ico'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/anaconda3/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "/root/anaconda3/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
>     return await self.app(scope, receive, send)
>   File "/root/anaconda3/lib/python3.7/site-packages/fastapi/applications.py", line 269, in __call__
>     await super().__call__(scope, receive, send)
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
>     raise exc
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
>     await self.app(scope, receive, send)
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 93, in __call__
>     raise exc
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
>     await self.app(scope, receive, sender)
>   File "/root/anaconda3/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
>     raise e
>   File "/root/anaconda3/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
>     await self.app(scope, receive, send)
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 670, in __call__
>     await route.handle(scope, receive, send)
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 266, in handle
>     await self.app(scope, receive, send)
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 68, in app
>     await response(scope, receive, send)
>   File "/root/anaconda3/lib/python3.7/site-packages/starlette/responses.py", line 321, in __call__
>     raise RuntimeError(f"File at path {self.path} does not exist.")
> RuntimeError: File at path ../favicon.ico does not exist.
> ```

感谢反馈问题，已修复该问题，更新到 0.0.66 版本使用
