### ISSUE TITLE
访问同花顺成分时个别概念返回服务器错误

### ISSUE THREAD

**Issue by Cuiqs76** [akfamily/aktools#71]
访问接口：stock_board_concept_cons_ths
symbol = WiFi 6 

报以下错误， 用python 直接访问正常。

(base) PS C:\Users\cuiqs> python -m aktools
点击打开接口导览：http://127.0.0.1:8080/docs
[32mINFO[0m:     Started server process [[36m18232[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8080[0m (Press CTRL+C to quit)
[32mINFO[0m:     127.0.0.1:62872 - "[1mGET /api/public/stock_board_concept_cons_ths?symbol=WiFi%206 HTTP/1.1[0m" [91m500 Internal Server Error[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\exceptions.py", line 87, in __call__
    raise exc
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\concurrency.py", line 45, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\aktools\core\api.py", line 128, in root
    received_df = eval("ak." + item_id + f"({eval_str})")
  File "<string>", line 1, in <module>
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 143, in stock_board_concept_cons_ths
    stock_board_ths_map_df[stock_board_ths_map_df["概念名称"] == symbol]["网址"]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by jindaxiang** [comment]
> 访问接口：stock_board_concept_cons_ths symbol = WiFi 6
> 
> 报以下错误， 用python 直接访问正常。
> 
> (base) PS C:\Users\cuiqs> python -m aktools 点击打开接口导览：http://127.0.0.1:8080/docs �[32mINFO�[0m: Started server process [�[36m18232�[0m] �[32mINFO�[0m: Waiting for application startup. �[32mINFO�[0m: Application startup complete. �[32mINFO�[0m: Uvicorn running on �[1mhttp://127.0.0.1:8080�[0m (Press CTRL+C to quit) �[32mINFO�[0m: 127.0.0.1:62872 - "�[1mGET /api/public/stock_board_concept_cons_ths?symbol=WiFi%206 HTTP/1.1�[0m" �[91m500 Internal Server Error�[0m �[31mERROR�[0m: Exception in ASGI application Traceback (most recent call last): File "d:\Users\cuiqs\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi result = await app(self.scope, self.receive, self.send) File "d:\Users\cuiqs\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in **call** return await self.app(scope, receive, send) File "d:\Users\cuiqs\anaconda3\lib\site-packages\fastapi\applications.py", line 261, in **call** await super().**call**(scope, receive, send) File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\applications.py", line 119, in **call** await self.middleware_stack(scope, receive, send) File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in **call** raise exc File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in **call** await self.app(scope, receive, _send) File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\middleware\cors.py", line 84, in **call** await self.app(scope, receive, send) File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\exceptions.py", line 87, in **call** raise exc File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\exceptions.py", line 76, in **call** await self.app(scope, receive, sender) File "d:\Users\cuiqs\anaconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in **call** raise e File "d:\Users\cuiqs\anaconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in **call** await self.app(scope, receive, send) File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\routing.py", line 659, in **call** await route.handle(scope, receive, send) File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle await self.app(scope, receive, send) File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app response = await func(request) File "d:\Users\cuiqs\anaconda3\lib\site-packages\fastapi\routing.py", line 227, in app raw_response = await run_endpoint_function( File "d:\Users\cuiqs\anaconda3\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function return await run_in_threadpool(dependant.call, **values) File "d:\Users\cuiqs\anaconda3\lib\site-packages\starlette\concurrency.py", line 45, in run_in_threadpool return await anyio.to_thread.run_sync(func, *args) File "d:\Users\cuiqs\anaconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable, File "d:\Users\cuiqs\anaconda3\lib\site-packages\anyio_backends_asyncio.py", line 818, in run_sync_in_worker_thread return await future File "d:\Users\cuiqs\anaconda3\lib\site-packages\anyio_backends_asyncio.py", line 754, in run result = context.run(func, *args) File "d:\Users\cuiqs\anaconda3\lib\site-packages\aktools\core\api.py", line 128, in root received_df = eval("ak." + item_id + f"({eval_str})") File "", line 1, in File "d:\Users\cuiqs\anaconda3\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 143, in stock_board_concept_cons_ths stock_board_ths_map_df[stock_board_ths_map_df["概念名称"] == symbol]["网址"] IndexError: index 0 is out of bounds for axis 0 with size 0

感谢反馈问题，升级到 AKTools 0.0.67 已经修复该问题

**Comment by Cuiqs76** [comment]
我升级到0.0.067后，启动不了。报告故障:
(base) PS C:\Users\p52s> python -m aktools
点击打开接口导览：http://127.0.0.1:8080/docs
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\anaconda3\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "d:\anaconda3\lib\site-packages\uvicorn\main.py", line 437, in main
    run(app, **kwargs)
  File "d:\anaconda3\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "d:\anaconda3\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "d:\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "d:\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "d:\anaconda3\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "d:\anaconda3\lib\site-packages\uvicorn\config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "d:\anaconda3\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "d:\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "d:\anaconda3\lib\site-packages\aktools\run.py", line 12, in <module>
    from core import app_core
  File "d:\anaconda3\lib\site-packages\aktools\core\__init__.py", line 3, in <module>
    from .api import app_core
  File "d:\anaconda3\lib\site-packages\aktools\core\api.py", line 155, in <module>
    short_path = get_template_path()
  File "d:\anaconda3\lib\site-packages\aktools\datasets.py", line 20, in get_template_path
    with resources.path("aktools.assets", "html") as f:
  File "d:\anaconda3\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "d:\anaconda3\lib\importlib\resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
PermissionError: [Errno 13] Permission denied: 'd:\\anaconda3\\lib\\site-packages\\aktools\\assets\\html'

1. 我以为是C盘原因，全部重装到D盘也不行，
2. 改了文件夹只读也不行
python: 3.10.5
anacondar3: 2022.05
Os: windows10

安装过程中，跳出一下红色警告：
![image](https://user-images.githubusercontent.com/13130628/173124749-65ca3e2f-d54a-43e4-805c-a91c29b0e09e.png)
然后我装了：ruamel-yaml  依然不能运行。
